swagger: '2.0'
info:
  title: Product Catalogue
  version: '1.0'
  description: Manages products in the catalogue.
basePath: /api
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
tags:
  - name: Catalogue
    description: The product catalogue.
  - name: Product
    description: A single product in the catalogue.
paths:
  /catalogue:
    get:
      operationId: get all products
      summary: Get all of the products.
      tags:
        - Catalogue
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      operationId: create new product
      summary: Create a new product.
      tags:
        - Catalogue
      responses:
        '201':
          description: >-
            OK - Product created.  URI of product will be available in the "uri"
            field
          schema:
            $ref: '#/definitions/Product'
        '422':
          description: Error - Product ID already exists.
      parameters:
        - $ref: '#/parameters/product'
  '/catalogue/product/{id}':
    get:
      operationId: get product
      summary: Get a product's details.
      tags:
        - Product
      responses:
        '200':
          description: The item matching the given ID.
          schema:
            $ref: '#/definitions/Product'
        '404':
          $ref: '#/responses/404'
    put:
      operationId: update product
      summary: Update a product's details.
      tags:
        - Product
      responses:
        '204':
          description: OK - Product updated.
        '404':
          $ref: '#/responses/404'
        '409':
          description: >-
            Error - ID in body does not match the ID in the path (changing the ID is not allowed).
      parameters:
        - $ref: '#/parameters/product'
    delete:
      operationId: delete product
      summary: Delete a product from the catalogue.
      tags:
        - Product
      responses:
        '204':
          description: OK - Product deleted.
        '404':
          $ref: '#/responses/404'
    parameters:
      - name: id
        in: path
        description: Product's ID
        required: true
        type: string
responses:
  '404':
    description: Error - No product matching the given ID was found.
parameters:
  product:
    name: product
    in: body
    required: true
    schema:
      $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    description: Details for a product in the catalogue.
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      listPrice:
        type: number
        format: double
      uri:
        type: string
    required:
      - id
      - name
